### ISSUE TITLE
the following icons are missing

### ISSUE THREAD

**Issue by b-user** [Bluewave2/legacy-4.3.8-qBittorrent#1]
"folder-documents.svg"
"hash.svg"
"loading.svg"
"mail-inbox.svg"
"name.svg"
"plugins.svg"
"reannounce.svg"

**Comment by Bluewave2** [comment]
items such as hash.svg do not have an equivalent in the older version, I'll see what i can do

**Comment by Bluewave2** [comment]
Implemented , thank you!

**Comment by Bluewave2** [comment]
> Probably "qbittorrent.svg" is missing. Presumably used in macOS. https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/mainwindow.cpp#L143C14-L143C14
> 
> The details are unknown to me.
> 
> Can you test this assumption?

![image](https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/assets/83724034/de8b6312-4ee2-4f3c-b4e7-da45f4a63add)

Finally tested it, due to how I made this theme, there is no override needed so it just uses the default image
