### ISSUE TITLE
list of useless files

### ISSUE THREAD

**Issue by b-user** [Bluewave2/legacy-4.3.8-qBittorrent#2]
build-icons/*
flags/*

qbittorrent.ico
qbittorrent_file.ico

README.md

loading.png
mascot.png
sphere.png
sphere2.png
splash.png

icons.qrc

application-rss+xml.svg
checked.svg
collapse.svg
completed.svg
dialog-cancel.svg
dialog-information.svg
document-edit.svg
document-edit-verify.svg
document-encrypt.svg
document-import.svg
document-new.svg
document-properties.svg
document-save.svg
downloading_small.svg
edit-clear-history.svg
edit-cut.svg
edit-delete.svg
edit-paste.svg
expand.svg
fileicon.svg
FIXTHIS.svg
folder-download.svg
gear32.svg
help-about_NOTTHIS.svg
help-contents_notthis.svg
inode-directory.svg
kt-set-max-download-speed.svg
kt-set-max-upload-speed.svg
mail-folder-inbox.svg
mail-mark-read.svg
office-chart-line.svg
qbittorrent-tray-with-font.svg
ratio.svg
resumed.svg
seeding.svg
services.svg
stopped.svg
system-log-out.svg
tab-close.svg
task-ongoing.svg
text-plain.svg
tools-report-bug.svg
view-calendar-journal.svg
view-categories_NOTTHIS.svg
view-filter.svg
webui.svg

**Comment by Bluewave2** [comment]
stopped.svg was not safe to remove (used in transfer list) rest seems ok. Thank you

**Comment by Bluewave2** [comment]
No apology necessary, it happens :)

**Comment by Bluewave2** [comment]
> "legacy-4.3.8-qBittorrent-bluewave2-v1.18.qbtheme" contains "completed.svg". @Bluewave2, сould you tell me, please, where "completed.svg" (but not "checked-completed.svg") is used? I couldn't find this place.

could be my mistake , I copied some of them since sometimes I needed the same .svg for 2 icon names, I'll check it out when I have time.
