### ISSUE TITLE
return TransferList coloring to BW

### ISSUE THREAD

**Issue by b-user** [Bluewave2/legacy-4.3.8-qBittorrent#3]
You can also return the color of the "TransferList" to black and white
[config.json.txt](https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/files/11892352/config.json.txt)

**Comment by Bluewave2** [comment]
Version 4.3.8 has colored transfer statuses such as downloading so I'm not gonna make it all black, however this made me notice some issues with other transfer statuses so I fixed them. Thank you
