### ISSUE TITLE
"stoppeddownloaded" is purple.

### ISSUE THREAD

**Issue by b-user** [Bluewave2/legacy-4.3.8-qBittorrent#8]
In qbit 5.0.0, the line with the "stoppeddownloaded" status is purple.

![460](https://github.com/user-attachments/assets/7d581a01-8fed-4bb4-8c06-04a1e59020f6)
![500](https://github.com/user-attachments/assets/b255805c-dc89-47f6-b502-e87f90975979)

to work in 5.0.0 and be compatible with 4.5.0+, please "duplicate" the values for

TransferList.PausedDownloading --> TransferList.StoppedDownloading
and
TransferList.PausedUploading --> TransferList.StoppedUploading

something like this:
"TransferList.PausedDownloading": "#FA8072",
"TransferList.StoppedDownloading": "#FA8072",
"TransferList.PausedUploading": "#00008B",
"TransferList.StoppedUploading": "#00008B",

**Comment by Bluewave2** [comment]
Will take a look when I have the time.

**Comment by Bluewave2** [comment]
https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/pull/9 merged and fix is live https://github.com/Bluewave2/legacy-4.3.8-qBittorrent/releases/tag/v1.20
